db:
  image: microsoft/mssql-server-linux
  ports:
     - "1433:1433"
  environment:
    - MSSQL_SA_PASSWORD=Password01
    - ACCEPT_EULA=Y

app:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  links:
      - db
  volumes:
    - /usr/Avalon:/usr/Avalon
  ports:
    - "8000:8000"
  environment:
    - DB_NAME=avalon
    - DB_USER=sa
    - DB_PASSWORD=Password01
    - DB_HOST=db
    - DB_PORT=1433