# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False, verbose_name='Numero')),
                ('first_name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=200, verbose_name='Apellido')),
                ('zip_code', models.CharField(max_length=200, verbose_name='Zip Code')),
            ],
            options={
                'verbose_name': 'Clientes',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False, verbose_name='Numero')),
                ('first_name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=200, verbose_name='Apellido')),
                ('zip_code', models.CharField(max_length=200, verbose_name='Zip Code')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False, verbose_name='Numero')),
                ('due_date', models.DateField(verbose_name='Fecha Realizacion')),
                ('ship_date', models.DateField(verbose_name='Fecha Envio')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Customer', verbose_name='Cliente')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False, verbose_name='Numero')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Order', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False, verbose_name='Numero')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Precio')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Parte',
                'verbose_name_plural': 'Partes',
            },
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Part', verbose_name='Parte'),
        ),
    ]
